services:
  miniclouds:
    container_name: miniclouds
    image: ghcr.io/svetliomitev/miniclouds:latest
    ports:
      - "18888:80"
    volumes:
      - mc_app:/var/www/html
    restart: unless-stopped

volumes:
  mc_app: